// <auto-generated />
using System;
using CSTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSTest.Migrations
{
    [DbContext(typeof(AppDbContent))]
    [Migration("20191015141114_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview8.19405.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSTest.DateTemp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("daysNumber")
                        .HasColumnType("int");

                    b.Property<double>("temperature")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("dateTemps");
                });

            modelBuilder.Entity("CSTest.HouseDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("consumptionHouse")
                        .HasColumnType("float");

                    b.Property<int>("daysNumber")
                        .HasColumnType("int");

                    b.Property<int?>("houseNameid")
                        .HasColumnType("int");

                    b.Property<DateTime>("localDateTemp")
                        .HasColumnType("datetime2");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("houseNameid");

                    b.ToTable("houseDetails");
                });

            modelBuilder.Entity("CSTest.Models.HouseName", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("houseNames");
                });

            modelBuilder.Entity("CSTest.Models.PlantDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("consumptionPlant")
                        .HasColumnType("float");

                    b.Property<int>("daysNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("localDateTemp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("plantNameid")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("plantNameid");

                    b.ToTable("plantDetails");
                });

            modelBuilder.Entity("CSTest.Models.PlantName", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("plantNames");
                });

            modelBuilder.Entity("CSTest.HouseDetail", b =>
                {
                    b.HasOne("CSTest.Models.HouseName", "houseName")
                        .WithMany("listHouseDetails")
                        .HasForeignKey("houseNameid");
                });

            modelBuilder.Entity("CSTest.Models.PlantDetail", b =>
                {
                    b.HasOne("CSTest.Models.PlantName", "plantName")
                        .WithMany("listPlantDetails")
                        .HasForeignKey("plantNameid");
                });
#pragma warning restore 612, 618
        }
    }
}
